before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build lab01/cs103S2018_lab01.tex
- latexmk -pdf -outdir=_build lab02/cs103S2018_lab02.tex
- latexmk -pdf -outdir=_build lab03/cs103S2018_lab03.tex
- latexmk -pdf -outdir=_build lab04/cs103S2018_lab04.tex
- latexmk -pdf -outdir=_build lab05/cs103S2018_lab05.tex
- latexmk -pdf -outdir=_build lab06/cs103S2018_lab06.tex
- latexmk -pdf -outdir=_build lab07/cs103S2018_lab07.tex
- latexmk -pdf -outdir=_build lab08/cs103S2018_lab08.tex
- latexmk -pdf -outdir=_build practical01/cs103S2018_practical01.tex
- latexmk -pdf -outdir=_build practical02/cs103S2018_practical02.tex
- latexmk -pdf -outdir=_build practical03/cs103S2018_practical03.tex
- latexmk -pdf -outdir=_build practical04/cs103S2018_practical04.tex
- latexmk -pdf -outdir=_build practical05/cs103S2018_practical05.tex
- latexmk -pdf -outdir=_build practical06/cs103S2018_practical06.tex
- latexmk -pdf -outdir=_build practical07/cs103S2018_practical07.tex
- latexmk -pdf -outdir=_build quiz01/cs103S2018_studyguide_quiz01.tex
- latexmk -pdf -outdir=_build quiz01/cs103S2018_studyguide_exam01.tex
deploy:
  provider: releases
  api_key:
    secure: bEUjP3sVFNL6vEkn9wyLCGrL9KuKDsARIIvb/fftOLy+fqtowad0X0IhnGelSG680hG2eS4/Bnpoi51hH5utrQBlxqMIlbr0buTHuH+DAmPGyoVWoVVBHWH0fH5EILjNrijjwGfOIPv5MHgB4TNoCVHRwJODKwKFVNVro+/aUzrTQRXIJOHyckySeVxGpx+zNCZ6mh38kFwNtEQ3npM28TJ1v2mqI+Q3SjGy/AsRbSU2JDfSvWQ/KYBxx950owwjZwz88q93CwQGBS/PRrUYhdwxnHfvAwFH0M29vKyq4O+PrUEcxZvijguSfVVZlsl+5jpfHzEkFdEapBwlgNwF11K0bMlHDfCBvk4PyOTmPLM1G3S9Ire6f/99bSQ1565ltvc57+M2n9Orc7bcBPa5tLzNxd6GbNxdYNFQzjOSU1mze4v+TKq8ZizHF/9mWfFYdZSDt7fzFa8D42UYLnMnvZ3RvZOh5iBpMrRoPzpe4KSJvt6ajtxlXfB4oglDwr6OIJW8Hu6zY/vMzUDAY9A9B3TaYfJOI3u4JvWp6JuMvM+QyVrCgsTcqzuWKU6jeQFEk7LlhJXLIx760aGybQHjc6qHWiT0yK7p8NOhLK4Ah/wAqTB7TCsKFu+niR+MKzxnRUr0KHrQxIxglijd62GkKWHsPxyYUMsCduuh2gLXC1Q=
  file:
    - _build/cs103S2018_lab01.pdf
    - _build/cs103S2018_lab02.pdf
    - _build/cs103S2018_lab03.pdf
    - _build/cs103S2018_lab04.pdf
    - _build/cs103S2018_lab05.pdf
    - _build/cs103S2018_lab06.pdf
    - _build/cs103S2018_lab07.pdf
    - _build/cs103S2018_lab08.pdf
    - _build/cs103S2018_practical01.pdf
    - _build/cs103S2018_practical02.pdf
    - _build/cs103S2018_practical03.pdf
    - _build/cs103S2018_practical04.pdf
    - _build/cs103S2018_practical05.pdf
    - _build/cs103S2018_practical06.pdf
    - _build/cs103S2018_practical07.pdf
    - _build/cs103S2018_studyguide_quiz01.pdf
    - _build/cs103S2018_studyguide_exam01.pdf
  skip_cleanup: true
  on:
    tags: true
